//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juego_MVC_bomber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOTES()
        {
            this.IMAGENES_LOTE = new HashSet<IMAGENES_LOTE>();
            this.RESULTADOS_JUEGO = new HashSet<RESULTADOS_JUEGO>();
            this.TORNEOS = new HashSet<TORNEOS>();
        }
    
        public int IdLote { get; set; }
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
        public bool EsDefault { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<int> AprobadoPor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGENES_LOTE> IMAGENES_LOTE { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual USUARIOS USUARIOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADOS_JUEGO> RESULTADOS_JUEGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TORNEOS> TORNEOS { get; set; }
    }
}
