//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juego_MVC_bomber.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class the_match_leagueEntities : DbContext
    {
        public the_match_leagueEntities()
            : base("name=the_match_leagueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IMAGENES_LOTE> IMAGENES_LOTE { get; set; }
        public virtual DbSet<LOTES> LOTES { get; set; }
        public virtual DbSet<RESULTADOS_JUEGO> RESULTADOS_JUEGO { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<TORNEO_PARTICIPANTES> TORNEO_PARTICIPANTES { get; set; }
        public virtual DbSet<TORNEOS> TORNEOS { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_AprobarLote(Nullable<int> idLote, Nullable<int> idAdmin)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("IdLote", idLote) :
                new ObjectParameter("IdLote", typeof(int));
    
            var idAdminParameter = idAdmin.HasValue ?
                new ObjectParameter("IdAdmin", idAdmin) :
                new ObjectParameter("IdAdmin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AprobarLote", idLoteParameter, idAdminParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_EliminarLote(Nullable<int> idLote)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("IdLote", idLote) :
                new ObjectParameter("IdLote", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarLote", idLoteParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_ObtenerLotesDisponibles_Result> SP_ObtenerLotesDisponibles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerLotesDisponibles_Result>("SP_ObtenerLotesDisponibles");
        }
    
        public virtual ObjectResult<SP_ObtenerLotesPendientes_Result> SP_ObtenerLotesPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerLotesPendientes_Result>("SP_ObtenerLotesPendientes");
        }
    
        public virtual ObjectResult<SP_ObtenerMejoresPuntajes_Result> SP_ObtenerMejoresPuntajes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerMejoresPuntajes_Result>("SP_ObtenerMejoresPuntajes");
        }
    
        public virtual ObjectResult<SP_ObtenerPodio_Result> SP_ObtenerPodio(Nullable<int> idLote)
        {
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("IdLote", idLote) :
                new ObjectParameter("IdLote", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerPodio_Result>("SP_ObtenerPodio", idLoteParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TieneLotePendiente(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TieneLotePendiente", idUsuarioParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_CrearTorneo_Result> SP_CrearTorneo(string nombre, Nullable<int> idLote, Nullable<int> idAdmin, Nullable<int> maxJugadores, Nullable<int> tiempoLimite)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var idLoteParameter = idLote.HasValue ?
                new ObjectParameter("IdLote", idLote) :
                new ObjectParameter("IdLote", typeof(int));
    
            var idAdminParameter = idAdmin.HasValue ?
                new ObjectParameter("IdAdmin", idAdmin) :
                new ObjectParameter("IdAdmin", typeof(int));
    
            var maxJugadoresParameter = maxJugadores.HasValue ?
                new ObjectParameter("MaxJugadores", maxJugadores) :
                new ObjectParameter("MaxJugadores", typeof(int));
    
            var tiempoLimiteParameter = tiempoLimite.HasValue ?
                new ObjectParameter("TiempoLimite", tiempoLimite) :
                new ObjectParameter("TiempoLimite", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CrearTorneo_Result>("SP_CrearTorneo", nombreParameter, idLoteParameter, idAdminParameter, maxJugadoresParameter, tiempoLimiteParameter);
        }
    
        public virtual ObjectResult<SP_EstadisticasUsuario_Result> SP_EstadisticasUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EstadisticasUsuario_Result>("SP_EstadisticasUsuario", idUsuarioParameter);
        }
    
        public virtual int SP_GenerarCodigoTorneo(ObjectParameter codigo)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GenerarCodigoTorneo", codigo);
        }
    
        public virtual int SP_IniciarTorneo(Nullable<int> idTorneo, Nullable<int> idAdmin, ObjectParameter resultado)
        {
            var idTorneoParameter = idTorneo.HasValue ?
                new ObjectParameter("IdTorneo", idTorneo) :
                new ObjectParameter("IdTorneo", typeof(int));
    
            var idAdminParameter = idAdmin.HasValue ?
                new ObjectParameter("IdAdmin", idAdmin) :
                new ObjectParameter("IdAdmin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_IniciarTorneo", idTorneoParameter, idAdminParameter, resultado);
        }
    
        public virtual ObjectResult<SP_ObtenerParticipantesTorneo_Result> SP_ObtenerParticipantesTorneo(Nullable<int> idTorneo)
        {
            var idTorneoParameter = idTorneo.HasValue ?
                new ObjectParameter("IdTorneo", idTorneo) :
                new ObjectParameter("IdTorneo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerParticipantesTorneo_Result>("SP_ObtenerParticipantesTorneo", idTorneoParameter);
        }
    
        public virtual ObjectResult<SP_ObtenerPodioTorneo_Result> SP_ObtenerPodioTorneo(Nullable<int> idTorneo)
        {
            var idTorneoParameter = idTorneo.HasValue ?
                new ObjectParameter("IdTorneo", idTorneo) :
                new ObjectParameter("IdTorneo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerPodioTorneo_Result>("SP_ObtenerPodioTorneo", idTorneoParameter);
        }
    
        public virtual ObjectResult<SP_ObtenerTorneosActivos_Result> SP_ObtenerTorneosActivos(Nullable<int> idAdmin)
        {
            var idAdminParameter = idAdmin.HasValue ?
                new ObjectParameter("IdAdmin", idAdmin) :
                new ObjectParameter("IdAdmin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerTorneosActivos_Result>("SP_ObtenerTorneosActivos", idAdminParameter);
        }
    
        public virtual int SP_RegistrarResultadoTorneo(Nullable<int> idTorneo, Nullable<int> idUsuario, Nullable<int> puntuacion, Nullable<int> tiempo, Nullable<int> movimientos)
        {
            var idTorneoParameter = idTorneo.HasValue ?
                new ObjectParameter("IdTorneo", idTorneo) :
                new ObjectParameter("IdTorneo", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var puntuacionParameter = puntuacion.HasValue ?
                new ObjectParameter("Puntuacion", puntuacion) :
                new ObjectParameter("Puntuacion", typeof(int));
    
            var tiempoParameter = tiempo.HasValue ?
                new ObjectParameter("Tiempo", tiempo) :
                new ObjectParameter("Tiempo", typeof(int));
    
            var movimientosParameter = movimientos.HasValue ?
                new ObjectParameter("Movimientos", movimientos) :
                new ObjectParameter("Movimientos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarResultadoTorneo", idTorneoParameter, idUsuarioParameter, puntuacionParameter, tiempoParameter, movimientosParameter);
        }
    
        public virtual int SP_UnirseTorneo(string codigo, Nullable<int> idUsuario, ObjectParameter resultado, ObjectParameter mensaje)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UnirseTorneo", codigoParameter, idUsuarioParameter, resultado, mensaje);
        }
    }
}
