//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juego_MVC_bomber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADOS_JUEGO
    {
        public int IdResultado { get; set; }
        public int IdUsuario { get; set; }
        public int IdLote { get; set; }
        public int Puntuacion { get; set; }
        public int Tiempo { get; set; }
        public int Movimientos { get; set; }
        public bool Completado { get; set; }
        public System.DateTime FechaJuego { get; set; }
    
        public virtual LOTES LOTES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
