//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juego_MVC_bomber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORNEO_PARTICIPANTES
    {
        public int IdParticipacion { get; set; }
        public int IdTorneo { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaUnion { get; set; }
        public bool Listo { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public Nullable<int> Movimientos { get; set; }
        public Nullable<int> Posicion { get; set; }
        public bool Completado { get; set; }
        public Nullable<System.DateTime> FechaCompletado { get; set; }
    
        public virtual TORNEOS TORNEOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
