//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juego_MVC_bomber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORNEOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TORNEOS()
        {
            this.TORNEO_PARTICIPANTES = new HashSet<TORNEO_PARTICIPANTES>();
        }
    
        public int IdTorneo { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int IdLote { get; set; }
        public int IdAdmin { get; set; }
        public string Estado { get; set; }
        public int MaxJugadores { get; set; }
        public Nullable<int> TiempoLimite { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        public virtual LOTES LOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TORNEO_PARTICIPANTES> TORNEO_PARTICIPANTES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
